spring:
  application:
    name=big-event
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/big_event
    username: root
    password: abc123
    type: com.zaxxer.hikari.HikariDataSource
  data:
    redis:
      password: abc123
  servlet:
    multipart:
      max-file-size: 5MB
---
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.bootzero.big_event.bean
  configuration:
    map-underscore-to-camel-case: true
---
logging:
  level:
    com.bootzero.big_event.mapper: debug
---
myminio:
  endpoint: http://192.168.15.128:9000
  accessKey: Wua5Ddxndpva92RjzGvY
  secretKey: lsPpVapFxgDG0X6pClKUq16N7oSwSlcDcC9IqzZb
  bucket-name: big-event